const resourceDictionary = [
  {
    id: "ru-1",
    type: "phrase",
    term: "спасибо",
    translation: "tesekkurler",
    phrase: "спасибо за помощь",
    phraseTranslation: "yardim icin tesekkurler",
    language: "Russian",
    source: "System Catalog",
    title: "Built-in course catalog",
    savedAt: "Today",
    level: "Learning",
    note: "Rusça günlük teşekkür kalıbı.",
  },
  {
    id: "ru-2",
    type: "phrase",
    term: "пожалуйста",
    translation: "lutfen; rica ederim",
    phrase: "скажите, пожалуйста",
    phraseTranslation: "lutfen soyleyin",
    language: "Russian",
    source: "System Catalog",
    title: "Built-in course catalog",
    savedAt: "Today",
    level: "Review",
    note: "Rica ve nezaket bildirir.",
  },
  {
    id: "ru-3",
    type: "word",
    term: "привет",
    translation: "selam",
    phrase: "привет, как дела?",
    phraseTranslation: "selam, nasilsin?",
    language: "Russian",
    source: "System Catalog",
    title: "Built-in course catalog",
    savedAt: "Yesterday",
    level: "Learning",
    note: "Samimi karsilama sozu.",
  },
  {
    id: "ru-4",
    type: "phrase",
    term: "добрый день",
    translation: "iyi gunler",
    phrase: "добрый день, Анна",
    phraseTranslation: "iyi gunler, Anna",
    language: "Russian",
    source: "System Catalog",
    title: "Built-in course catalog",
    savedAt: "Yesterday",
    level: "Known",
    note: "E-posta ve günlük selamlamada kullanılır.",
  },
  {
    id: "ru-5",
    type: "word",
    term: "извините",
    translation: "affedersiniz",
    phrase: "извините за опоздание",
    phraseTranslation: "gecikme icin affedersiniz",
    language: "Russian",
    source: "System Catalog",
    title: "Built-in course catalog",
    savedAt: "Apr 27",
    level: "Learning",
    note: "Ozur ve dikkat cekme kalibi.",
  },
  {
    id: "ru-6",
    type: "phrase",
    term: "всё хорошо",
    translation: "her sey iyi",
    phrase: "да, всё хорошо",
    phraseTranslation: "evet, her sey iyi",
    language: "Russian",
    source: "System Catalog",
    title: "Built-in course catalog",
    savedAt: "Apr 27",
    level: "Review",
    note: "Kisa durum cevabi.",
  },
  {
    id: "ru-7",
    type: "word",
    term: "можно",
    translation: "mumkun; olur",
    phrase: "можно кофе?",
    phraseTranslation: "kahve alabilir miyim?",
    language: "Russian",
    source: "System Catalog",
    title: "Built-in course catalog",
    savedAt: "Apr 26",
    level: "Learning",
    note: "Izin isterken cok kullanilir.",
  },
  {
    id: "ru-8",
    type: "phrase",
    term: "до завтра",
    translation: "yarina kadar; yarin gorusuruz",
    phrase: "хорошо, до завтра",
    phraseTranslation: "tamam, yarin gorusuruz",
    language: "Russian",
    source: "System Catalog",
    title: "Built-in course catalog",
    savedAt: "Apr 26",
    level: "Known",
    note: "Vedalasma kalibi.",
  },
  {
    id: "ru-9",
    type: "word",
    term: "читать",
    translation: "okumak",
    phrase: "я читаю книгу",
    phraseTranslation: "kitap okuyorum",
    language: "Russian",
    source: "System Catalog",
    title: "Built-in course catalog",
    savedAt: "Apr 26",
    level: "Learning",
    note: "Düzenli fiil çekimi için temel örnek.",
  },
  {
    id: "ru-10",
    type: "word",
    term: "говорить",
    translation: "konuşmak",
    phrase: "мы говорим по-русски",
    phraseTranslation: "Rusça konuşuyoruz",
    language: "Russian",
    source: "System Catalog",
    title: "Built-in course catalog",
    savedAt: "Apr 26",
    level: "Learning",
    note: "Fiil çekimi ve dil ifadelerinde kullanılır.",
  },
  {
    id: "ru-11",
    type: "phrase",
    term: "у меня есть",
    translation: "bende var",
    phrase: "у меня есть вопрос",
    phraseTranslation: "bir sorum var",
    language: "Russian",
    source: "System Catalog",
    title: "Built-in course catalog",
    savedAt: "Apr 25",
    level: "Learning",
    note: "Sahiplik ifadesi için temel yapı.",
  },
  {
    id: "ru-12",
    type: "word",
    term: "нет",
    translation: "yok; hayır",
    phrase: "у меня нет времени",
    phraseTranslation: "vaktim yok",
    language: "Russian",
    source: "System Catalog",
    title: "Built-in course catalog",
    savedAt: "Apr 25",
    level: "Review",
    note: "Olumsuzluk ve genitif kullanımında temel kelime.",
  },
  {
    id: "ru-13",
    type: "word",
    term: "люди",
    translation: "insanlar",
    phrase: "здесь много людей",
    phraseTranslation: "burada çok insan var",
    language: "Russian",
    source: "System Catalog",
    title: "Built-in course catalog",
    savedAt: "Apr 24",
    level: "Learning",
    note: "Çoğul isim örneği.",
  },
  {
    id: "ru-14",
    type: "word",
    term: "один",
    translation: "bir",
    phrase: "один билет, пожалуйста",
    phraseTranslation: "bir bilet lütfen",
    language: "Russian",
    source: "System Catalog",
    title: "Built-in course catalog",
    savedAt: "Apr 24",
    level: "Learning",
    note: "Sayılar ve isim uyumu için kullanılır.",
  },
  {
    id: "ru-15",
    type: "word",
    term: "сегодня",
    translation: "bugün",
    phrase: "сегодня я дома",
    phraseTranslation: "bugün evdeyim",
    language: "Russian",
    source: "System Catalog",
    title: "Built-in course catalog",
    savedAt: "Apr 23",
    level: "Learning",
    note: "Zaman zarfı.",
  },
  {
    id: "ru-16",
    type: "word",
    term: "в",
    translation: "-de; içine",
    phrase: "я в школе",
    phraseTranslation: "okuldayım",
    language: "Russian",
    source: "System Catalog",
    title: "Built-in course catalog",
    savedAt: "Apr 23",
    level: "Review",
    note: "Yer ve yön ifadelerinde sık kullanılan edat.",
  },
  {
    id: "ru-17",
    type: "word",
    term: "с",
    translation: "ile; -den",
    phrase: "кофе с молоком",
    phraseTranslation: "sütlü kahve",
    language: "Russian",
    source: "System Catalog",
    title: "Built-in course catalog",
    savedAt: "Apr 22",
    level: "Learning",
    note: "Araç hâliyle kullanılan temel edat.",
  },
  {
    id: "ru-18",
    type: "word",
    term: "лучше",
    translation: "daha iyi",
    phrase: "так лучше",
    phraseTranslation: "böyle daha iyi",
    language: "Russian",
    source: "System Catalog",
    title: "Built-in course catalog",
    savedAt: "Apr 22",
    level: "Learning",
    note: "Karşılaştırma kalıbı.",
  },
  {
    id: "ru-19",
    type: "word",
    term: "мой",
    translation: "benim",
    phrase: "это мой дом",
    phraseTranslation: "bu benim evim",
    language: "Russian",
    source: "System Catalog",
    title: "Built-in course catalog",
    savedAt: "Apr 21",
    level: "Learning",
    note: "İyelik zamiri.",
  },
  {
    id: "ru-20",
    type: "phrase",
    term: "который час",
    translation: "saat kaç",
    phrase: "скажите, который час?",
    phraseTranslation: "saat kaç, söyler misiniz?",
    language: "Russian",
    source: "System Catalog",
    title: "Built-in course catalog",
    savedAt: "Apr 21",
    level: "Review",
    note: "Saat sorma kalıbı.",
  },
  {
    id: "en-1",
    type: "phrase",
    term: "make sure",
    translation: "emin olmak",
    phrase: "make sure it works",
    phraseTranslation: "calistigindan emin ol",
    language: "English",
    source: "System Catalog",
    title: "Built-in course catalog",
    savedAt: "Apr 25",
    level: "Learning",
    note: "Günlük iş ve mesaj dilinde yaygın.",
  },
  {
    id: "en-2",
    type: "word",
    term: "appointment",
    translation: "randevu",
    phrase: "make an appointment",
    phraseTranslation: "randevu almak",
    language: "English",
    source: "System Catalog",
    title: "Built-in course catalog",
    savedAt: "Apr 25",
    level: "Review",
    note: "Appointment genelde make/book ile kullanilir.",
  },
  {
    id: "en-3",
    type: "phrase",
    term: "take a break",
    translation: "mola vermek",
    phrase: "let's take a break",
    phraseTranslation: "hadi mola verelim",
    language: "English",
    source: "System Catalog",
    title: "Built-in course catalog",
    savedAt: "Apr 24",
    level: "Known",
    note: "Do yerine take ile kullanilir.",
  },
  {
    id: "es-1",
    type: "phrase",
    term: "por favor",
    translation: "lutfen",
    phrase: "un cafe, por favor",
    phraseTranslation: "bir kahve lutfen",
    language: "Spanish",
    source: "System Catalog",
    title: "Built-in course catalog",
    savedAt: "Apr 24",
    level: "Learning",
    note: "Siparis ve rica kalibi.",
  },
  {
    id: "es-2",
    type: "word",
    term: "quedar",
    translation: "bulusmak; kalmak",
    phrase: "quedamos manana",
    phraseTranslation: "yarin bulusalim",
    language: "Spanish",
    source: "System Catalog",
    title: "Built-in course catalog",
    savedAt: "Apr 23",
    level: "Review",
    note: "Buluşma ayarlarken kullanılır.",
  },
  {
    id: "de-1",
    type: "phrase",
    term: "gern",
    translation: "memnuniyetle",
    phrase: "ja, gern",
    phraseTranslation: "evet, memnuniyetle",
    language: "German",
    source: "System Catalog",
    title: "Built-in course catalog",
    savedAt: "Apr 22",
    level: "Learning",
    note: "Kisa ve dogal onay cevabi.",
  },
  {
    id: "de-2",
    type: "word",
    term: "Bescheid",
    translation: "haber; bilgi",
    phrase: "gib mir Bescheid",
    phraseTranslation: "bana haber ver",
    language: "German",
    source: "System Catalog",
    title: "Built-in course catalog",
    savedAt: "Apr 22",
    level: "Learning",
    note: "Günlük mesajlarda çok kullanılır.",
  },
  {
    id: "fr-1",
    type: "phrase",
    term: "s'il vous plait",
    translation: "lutfen",
    phrase: "l'addition, s'il vous plait",
    phraseTranslation: "hesap lutfen",
    language: "French",
    source: "System Catalog",
    title: "Built-in course catalog",
    savedAt: "Apr 21",
    level: "Known",
    note: "Restoran ve resmi rica kalibi.",
  },
  {
    id: "fr-2",
    type: "word",
    term: "rendez-vous",
    translation: "randevu; bulusma",
    phrase: "prendre rendez-vous",
    phraseTranslation: "randevu almak",
    language: "French",
    source: "System Catalog",
    title: "Built-in course catalog",
    savedAt: "Apr 21",
    level: "Review",
    note: "Prendre fiiliyle kalıplaşır.",
  },
];

const courseCatalog = [
  {
    id: "ru-fourman-alphabet",
    language: "Russian",
    title: "Alfabe ve okuma",
    description: "Yerleşik kurs kataloğundaki alfabe, okuma ve kısa kalıp alıştırmaları.",
    level: "Başlangıç",
    minutes: 10,
    itemIds: ["ru-3", "ru-4"],
    unit: "Hazırlık",
    activities: ["Harfleri tanı", "Ses eşleştir", "Okuma denemesi"],
  },
  ...[
    ["Nouns", "İsimlerin temel yapısı", ["ru-1"]],
    ["Nouns (continued)", "İsimleri cümlede tanıma", ["ru-2"]],
    ["Adjectives", "Sıfatları isimlerle kullanma", ["ru-3"]],
    ["Pronouns", "Ben, sen, o gibi zamirler", ["ru-4"]],
    ["Declension of Nouns, Adjectives and Pronouns", "Çekim mantığına giriş", ["ru-5"]],
    ["Genitive of Feminine Nouns", "Dişil isimlerde genitif", ["ru-6"]],
    ["Genitive of Neuter Nouns", "Nötr isimlerde genitif", ["ru-7"]],
    ["Dative of Masc., Fem., and Neuter Nouns", "Datif hâlini tanıma", ["ru-8"]],
    ["Verbs", "Fiillere giriş", ["ru-9", "ru-10"]],
    ["Shortened Adjectives", "Kısa sıfat biçimleri", ["ru-18"]],
    ["Verbs: Regular Conjugations and Accusative Case", "Düzenli fiil çekimleri", ["ru-9", "ru-10"]],
    ["Genitive of Adjectives", "Sıfatlarda genitif", ["ru-12"]],
    ["Dative and Accusative of Adjectives", "Sıfatlarda datif ve akuzatif", ["ru-7"]],
    ["Use of Negative and Genitive", "Olumsuzluk ve genitif kullanımı", ["ru-12"]],
    ["Plural of Nouns and Adjectives", "Çoğul isim ve sıfatlar", ["ru-13"]],
    ["Irregular Noun Declensions", "Düzensiz isim çekimleri", ["ru-13"]],
    ["Numerals", "Sayılar", ["ru-14"]],
    ["Numerals (continued)", "Sayılarla devam", ["ru-14", "ru-20"]],
    ["Verbs (continued)", "Fiillerle devam", ["ru-9", "ru-10"]],
    ["Prepositions", "Edatlara giriş", ["ru-16", "ru-17"]],
    ["Prepositions", "Edatları cümlede kullanma", ["ru-16", "ru-17"]],
    ["Instrumental and Prepositional Cases", "Araç ve yer hâlleri", ["ru-17"]],
    ["Comparison of Adjectives", "Sıfatlarda karşılaştırma", ["ru-18"]],
    ["Declension of Personal Pronouns", "Kişi zamirlerinin çekimi", ["ru-11"]],
    ["Declension of Possessive Pronouns", "İyelik zamirlerinin çekimi", ["ru-19"]],
    ["Declension of 'this', etc.", "İşaret zamirleri", ["ru-4"]],
    ["Declension of 'whose', etc.", "Soru zamirleri", ["ru-19"]],
    ["Aspects of the Verb", "Fiil görünüşleri", ["ru-9", "ru-10"]],
    ["Reflexive and Reciprocal Verbs", "Dönüşlü ve karşılıklı fiiller", ["ru-10"]],
    ["Participles", "Ortaçlar", ["ru-9"]],
    ["Gerund", "Ulaç yapıları", ["ru-9"]],
    ["Formation of Words", "Kelime türetme", ["ru-13"]],
    ["Irregular Verb Conjugations", "Düzensiz fiil çekimleri", ["ru-10"]],
    ["Adverbs", "Zarflar", ["ru-15"]],
    ["Diminutives and Augmentative Nouns", "Küçültme ve büyütme isimleri", ["ru-13"]],
    ["The Time", "Saat ve zaman ifadeleri", ["ru-20"]],
    ["Impersonal Expressions", "Kişisiz ifadeler", ["ru-11", "ru-12"]],
    ["Common Expressions and Interjections", "Yaygın ifadeler ve ünlemler", ["ru-1", "ru-2"]],
  ].map(([title, description, itemIds], index) => ({
    id: `ru-fourman-lesson-${index + 1}`,
    language: "Russian",
    title: `Ders ${index + 1}: ${description}`,
    sourceTitle: title,
    description: `Sistem kataloğu: ${title}. Kısa ders akışı.`,
    level: index < 12 ? "Başlangıç" : index < 28 ? "Temel" : "Orta",
    minutes: index < 12 ? 8 : index < 28 ? 10 : 12,
    itemIds,
    unit: index < 8 ? "Temel yapı" : index < 18 ? "Çekim ve fiil" : index < 28 ? "Hâller ve cümle" : "İleri okuma",
    activities: ["Kelime ısınması", "Kısa konu", "Cümle kur", "Mini test"],
  })),
  {
    id: "en-daily",
    language: "English",
    title: "Günlük İngilizce",
    description: "Mesajlarda ve iş akışında sık kullanılan İngilizce kalıplar.",
    level: "Başlangıç",
    minutes: 7,
    itemIds: ["en-1", "en-2", "en-3"],
  },
  {
    id: "es-daily",
    language: "Spanish",
    title: "Günlük İspanyolca",
    description: "Sipariş verme ve buluşma ayarlama için temel kalıplar.",
    level: "Başlangıç",
    minutes: 6,
    itemIds: ["es-1", "es-2"],
  },
  {
    id: "de-daily",
    language: "German",
    title: "Günlük Almanca",
    description: "Kısa onaylar ve haber verme kalıpları.",
    level: "Başlangıç",
    minutes: 6,
    itemIds: ["de-1", "de-2"],
  },
  {
    id: "fr-daily",
    language: "French",
    title: "Günlük Fransızca",
    description: "Rica, restoran ve randevu kalıpları.",
    level: "Başlangıç",
    minutes: 6,
    itemIds: ["fr-1", "fr-2"],
  },
];
